ppy/osu-queue-score-statistics

osu.Server.Queues.ScoreStatisticsProcessor.Tests/StatisticsUpdateTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/DifficultyAttributeExtensions.cs, osu.Server.Queues.ScoreStatisticsProcessor/LegacyModsHelper.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/Beatmap.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/BeatmapDifficultyAttribute.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScore.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScoreInfo.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScorePerformance.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/PerformanceProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsProcessor.cs
```sql
create table solo_scores_performance
(
`score_id` bigint unsigned not null
primary key,
`pp` double(8, 2)
);
```
For the time being I'm querying the `osu_beatmaps` and `osu_beatmap_difficulty_attribs` tables every time, which is expensive but probably not too bad for the time being. This will need to be optimised in the future - either via the way osu-performance does it (querying all attributes at once) or by calculating attributes in-line which will be required anyway once we start adjusting for lazer mod settings.
=> Add performance processor

osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScoreInfo.cs
Separating this one so there's no inter-dependencies between other PRs.
=> Add build_id to SoloScoreInfo

osu.Server.Queues.ScorePump/ImportHighScores.cs, osu.Server.Queues.ScorePump/PumpAllScores.cs, osu.Server.Queues.ScorePump/WatchNewScores.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/SerialisationTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/StatisticsUpdateTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScore.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScorePerformance.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/PerformanceProcessor.cs
The next step is to deploy this on production. However I don't want to write to the main table just yet (to keep things completely separate between lazer and legacy scores), to allow for testing out performance and structural changes without worrying about locking the whole table.
This will allow me to create different named temporary tables to test again. Haven't bothered with `solo_scores_process_history` just yet as it is out of scope for the initial testing.
=> Move table name specifications to constants

osu.Server.Queues.ScorePump/ImportHighScores.cs
They should not ever be empty strings, but some legacy scores have this in the database itself. Rather than leaving parsing to dapper (which will hard bail during enumeration) let's parse this ourselves and handle with a fallback.
Have tested this on production data to fix the issue. Still running strong after ~30m scores.
=> Fix enum parse failure if `rank` is an empty string

osu.Server.Queues.ScorePump/ImportHighScores.cs
Still using dapper for the outer query, but that's less of an issue.
This brings things from ~690/s to 1200/s. Still not super amazing (limited by 1xRTT per insert) but it's an improvement. The new structure will lend itself better to future optimisations, too.
```csharp
Written up to 7930516 (+2692 rows 1346/s)
Retrieving next 10000 scores starting from 7950567
Written up to 7961249 (+2854 rows 1427/s)
Written up to 7990932 (+2655 rows 1327/s)
Written up to 8018117 (+2773 rows 1386/s)
Written up to 8047042 (+2889 rows 1444/s)
Retrieving next 10000 scores starting from 8053148
Written up to 8075805 (+2817 rows 1408/s)
Written up to 8094364 (+1714 rows 857/s)
Written up to 8119163 (+2457 rows 1228/s)
Written up to 8149078 (+2842 rows 1421/s)
Retrieving next 10000 scores starting from …
```
=> Optimise insert performance by batching transactions and using prepared statements

osu.Server.Queues.ScorePump/ImportHighScores.cs
Database defines all these as `unsigned smallint`.
```csharp
Unhandled exception. System.Data.DataException: Error parsing column 10 (countgeki=43432 - UInt16)
---> System.OverflowException: Arithmetic operation resulted in an overflow.
at Deserialize6de5264b-9708-4784-9a2c-efbdf4d94bd2(IDataReader )
--- End of inner exception stack trace ---
at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3706
at Deserialize6de5264b-9708-4784-9a2c-efbdf4d94bd2(IDataReader )
at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext()
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at …
```
=> Fix crash from unsigned type mismatches overflowing

osu.Server.Queues.ScoreStatisticsProcessor.Tests/StatisticsUpdateTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/PerformanceProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayTimeProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsProcessor.cs
The basics just to get the ball rolling.
We may want to start sending more accurate fail time data from lazer (ie. actual point in gameplay of failure, either as a 0..1 range or as a raw millisecond value based on gameplay time).
=> Add play time processor

osu.Server.Queues.ScorePump/ImportHighScores.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScoreLegacyIDMap.cs
Not yet tested, PRing for discussion. Not 100% on the naming.
=> Add support to `ImportHighScores` to populate old-new mapping pairs

osu.Server.Queues.ScorePump/ImportHighScores.cs
Importantly, scores from the same beatmap need to be in the same batch such that the edge case where the `timestamp` is equal for two scores for the same beatmap, the `score_id` will be in correct sequentual order to maintain stable ordering.
Each batch (of 50,000 read scores) is run sequentially, so no special handling is required on the edges of batches.
Before: 7-800 scores per second
After: 8,000 scores per second
Now at the point of replication being the bottleneck, so I'm happy with this where it is for now.
=> Use partitioning to allow for parallelised insertion

osu.Server.Queues.ScorePump/ImportHighScores.cs
worked well until proxysql went and fucking crashed
=> Add automatic throttling to `ImportHighScores` based on replication slave latency

osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScoreInfo.cs
This wasn't being populated in `osu-web` (lazer) inserts, nor in the score pumper.
=> Mark `SoloScoreInfo.id` as non-serialised

osu.Server.Queues.ScoreStatisticsProcessor.Tests/LegacyModsHelperTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/LegacyModsHelper.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/PerformanceProcessor.cs
Two issues fixed with this one:
1. The old `LegacyModsHelper.keyMods` value doubled up `Key1`, but intended to use `KeyCoop` for that last one.
2. It didn't include all the new FL/FL+HD combos.
=> Fix mod masking differences from osu-performance

osu.Server.Queues.ScorePump/ImportHighScores.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayTimeProcessor.cs
Fixes https://github.com/ppy/osu-queue-score-statistics/issues/40
I'm not sure how you'd go about fixing the already imported scores server-side - fastest for me was reimporting all scores.
Have tested to make sure the score processors are able to run.
=> Import highscore date into `score->data->ended_at`

osu.Server.Queues.ScoreStatisticsProcessor/LegacyDatabaseHelper.cs
Discovered this as I'm dockerising my sr/pp calculator, where my databases aren't named "osu".
=> Fix incorrect database name in tables

osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
I've made it opt-in instead of opt-out to avoid any chance of incorrectly running and breaking stuff. Hopefully that's okay for now (will require updates to any existing usages of the processor or scorepump).
=> Add environment variable to enable processing user totals

.github/workflows/pack.yml
Same workflow as osu-web, but also added builds for the production branch.
- Push as git tag on git tag
- Push as latest on git tag, if tag doesn't contain a -
- Push as master and latest-dev on commit to master
- Push as production on commit to production
- Push as git sha on commit to master or production
Also added builds for pppy/osu-queue-score-pump. I know it's temporary but it didn't cost much
=> 👷 Add Docker builds

osu.Server.Queues.ScorePump/Queue/WatchNewScores.cs
This was brought up in Discord a few days ago and still hasn't been fixed, thought I'd do it myself.
=> Fix `watch` command failing with empty `solo_scores_process_history` table

osu.Server.Queues.ScoreStatisticsProcessor/Models/UserStats.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MaxComboProcessor.cs
This is hit by https://osu.ppy.sh/users/3909293/mania
```
diffcalc-sheet-generator-ppcalc-1     | Unhandled exception. System.Data.DataException: Error parsing column 21 (max_combo=35512 - UInt16)
diffcalc-sheet-generator-ppcalc-1     |  ---> System.OverflowException: Arithmetic operation resulted in an overflow.
diffcalc-sheet-generator-ppcalc-1     |    at Deserialize3ea6bb68-1c57-4ca9-b908-aa2fb993cdd6(IDataReader )
diffcalc-sheet-generator-ppcalc-1     |    --- End of inner exception stack trace ---
diffcalc-sheet-generator-ppcalc-1     |    at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3706
diffcalc-sheet-generator-ppcalc-1     |    at Deserialize3ea6bb68-1c57-4ca9-b908-aa2fb993cdd6(IDataReader ) …
```
=> Fix `max_combo` overflowing on database reads

.github/workflows/pack.yml
Since we're going to be using `release` for consistency across projects. The branch already exists and has been pushed from `production`. `production` still exists but will be removed when this PR is merged.
=> Change CI to use release branch for pushes

osu.Server.Queues.ScorePump/AddMaximumStatisticsToLazerScores.cs, osu.Server.Queues.ScorePump/Program.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/StatisticsUpdateTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScore.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScoreInfo.cs
**This is a `release` branch pull request!!**
Also contains https://github.com/ppy/osu-queue-score-statistics/pull/74  
This has only been PR'd to this branch because it's expected to be executed only once.
The `add-maximum-statistics-to-lazer-scores` command adds the `maximum_statistics` dictionary to all scores in the database.
I previously asked for the last 10000 scores in the `solo_scores` table. Here's the results of running this command on them: https://drive.google.com/file/d/1cbcTZEBtU1GnM4-unCZF5g8LP9or4y4U/view?usp=sharing **This is a 10MB text file, be careful!!**
=> Backport: Add osu!lazer score `maximum_statistics` upgrade command

osu.Server.Queues.ScorePump/Queue/ImportHighScores.cs, osu.Server.Queues.ScorePump/osu.Server.Queues.ScorePump.csproj, osu.Server.Queues.ScoreStatisticsProcessor.Tests/osu.Server.Queues.ScoreStatisticsProcessor.Tests.csproj, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Prereqs:
The purpose of this PR is to add the `MaximumStatistics` dictionary to imported scores.
- First we convert every hit type to the corresponding "accurate" version. For example for an `ok` result, the accurate version is `great` in osu/taiko/catch and `perfect` in mania. This is done via [`Ruleset.GetHitResults()`](https://github.com/ppy/osu/blob/289b6f1a583dc50e84cadff713808f43fddc7ff0/osu.Game/Rulesets/Ruleset.cs#L310-L339) as mentioned at in my [original PR](https://github.com/ppy/osu/pull/19939).
- Then, we compare the combo from those statistics to the combo in the `osu_beatmap_difficulty_attributes` table (`attrib_id = 9`), and add a `legacy_combo_increase` hit result to bring them up to the same level if they don't match. This only shows up for osu/mania - taiko/catch have …
=> Make the highscore importer provide the `MaximumStatistics` dictionary

osu.Server.Queues.ScorePump/Queue/ImportHighScores.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/osu.Server.Queues.ScoreStatisticsProcessor.Tests.csproj, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Prereqs:
Resolves https://github.com/ppy/osu-queue-score-statistics/issues/70
```
mysql> select * from osu_scores_high where replay=1 limit 1;
+----------+------------+---------+--------+----------+------+---------+----------+----------+-----------+-----------+-----------+---------+--------------+---------------------+---------+--------+--------+-----------------+
| score_id | beatmap_id | user_id | score  | maxcombo | rank | count50 | count100 | count300 | countmiss | countgeki | countkatu | perfect | enabled_mods | date                | pp      | replay | hidden | country_acronym |
+----------+------------+---------+--------+----------+------+---------+----------+----------+-----------+-----------+-----------+---------+--------------+---------------------+---------+--------+--------+---- …
```
=> Import `has_replay` and `legacy_score_id` into solo scores

osu.Server.Queues.ScorePump/Queue/ImportHighScores.cs
Re-closes https://github.com/ppy/osu-queue-score-statistics/issues/70
Two changes here:
See: https://github.com/ppy/osu-queue-score-statistics/pull/79#issuecomment-1235164890
```
mysql> select * from solo_scores where has_replay = 1 limit 1;
+----+---------+------------+------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+--------- …
```
=> Import `has_replay` into column instead

osu.Server.Queues.ScorePump/Queue/ImportHighScores.cs
May allow resuming from an error.
```csharp
root@es-scores-staging:~/import-high-scores# ./osu.Server.Queues.ScorePump queue import-high-scores --start-id 3449758
Sourcing from `osu`.`osu_scores_high` for osu starting from 3449758
Inserting into test_solo_scores
Increasing processing rate to 5100 due to latency of 2
Retrieving next 5100 scores from 3449758
Inserting up to 3,502,348 [0 /11] 0 inserted (+0 new 0/s)
ERROR: At least one tasks were faulted. Aborting for safety.
Running batches were processing up to 3502348.
0   3474112 - 3469676: FAILED (One or more errors occurred. (Duplicate entry '0-3474112' for key 'test_solo_scores_legacy_id_map.PRIMARY'))
1   3492035 - 3457612: FAILED (One or more errors occurred. (Duplicate entry '0-3492035' for key …
```
=> Add better error handling output

osu.Server.Queues.ScorePump/Queue/ImportHighScores.cs, osu.Server.Queues.ScorePump/Queue/WatchNewScores.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/StatisticsUpdateTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/ScoreItem.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScore.cs, osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Prereqs:
---
- `ProcessHistory` left as-is because it's defined as signed in the database.
- `ElasticScoreItem` left as-is because I'm not sure if there'd be any effects in changing the data type yet. Can be done later but isn't really what I'm trying to achieve.
=> Use `ulong` for highscore imports

osu.Server.Queues.ScorePump/Queue/UpgradeScores.cs, osu.Server.Queues.ScorePump/QueueCommands.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/osu.Server.Queues.ScoreStatisticsProcessor.Tests.csproj, osu.Server.Queues.ScoreStatisticsProcessor.sln.DotSettings, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Prereqs:
This PR ports a command which was pushed to the `release` branch, as well adds a new function to it to upgrade existing total score and accuracy values.
The command which was ported from the `release` branch is: https://github.com/ppy/osu-queue-score-statistics/blob/3b329c474e93f858ffad5c6b5d659ba115c7eff6/osu.Server.Queues.ScorePump/AddMaximumStatisticsToLazerScores.cs
This was done mainly because upgrading total score and accuracy values requires `MaximumStatistics` to be fully populated. And as we haven't yet blocked old lazer clients from submitting scores, some still have empty `MaximumStatistics`.
As for the total score upgrades... Of the 10000 scores that were provided to me, here's the full list of changes:
[changes.txt](https://github.com/ppy/osu-queue-score-statistics/fi …
=> Add command to upgrade scores

osu.Server.Queues.ScorePump/Queue/UpgradeScores.cs
On spinner-only catch maps like https://osu.ppy.sh/beatmapsets/23210#fruits/80895, there's no non-bonus judgements, and bonus judgements aren't counted into `MaximumStatistics` because there's no way to tell whether an `IgnoreMiss` was a large or small bonus.
=> Remove MaximumStatistics assert

osu.Server.Queues.ScorePump/Dockerfile, osu.Server.Queues.ScoreStatisticsProcessor/Dockerfile
These files are massive and unused in a headless context. Same workaround as applied in osu-difficulty-calculator. Seems to run fine.
=> 🔥 Remove unnecessary bloat in Docker image

osu.Server.Queues.ScorePump/Queue/ImportHighScores.cs
Already running on live deployment. Kinda replaces the resume support to a certain extent.
=> Add ability to skip existing legacy scores when running a full high score import

osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Stores/BeatmapStore.cs, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Makes use of https://github.com/ppy/osu/pull/20984 to fix the beatmap's ruleset not being populated before PP processing, for changes such as https://github.com/ppy/osu/pull/20558 to be able to check whether the beatmap is a convert or not.
=> Fix missing beatmap ruleset

osu.Server.Queues.ScoreStatisticsProcessor/Stores/BeatmapStore.cs
In my test database this would result in a failure like this:
```csharp
System.Collections.Generic.KeyNotFoundException: The given key '19' was not present in the dictionary.
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
at osu.Game.Rulesets.Osu.Difficulty.OsuDifficultyAttributes.FromDatabaseAttributes(IReadOnlyDictionary`2 values, IBeatmapOnlineInfo onlineInfo)
at osu.Server.Queues.ScoreStatisticsProcessor.Stores.BeatmapStore.GetDifficultyAttributesAsync(APIBeatmap beatmap, Ruleset ruleset, Mod[] mods, MySqlConnection connection, MySqlTransaction transaction) in /Users/dean/Projects/osu-queue-score-statistics/osu.Server.Queues.ScoreStatisticsProcessor/Stores/BeatmapStore.cs:line 83
```
Not 100% sure this is the right solution so please double-check.
=> Fix crash on looking up databased attributes when none are present

osu.Server.Queues.ScorePump/Queue/UpgradeScores.cs, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Note that lazer taiko scores' PP values will differ from what's expected by the deployed version of `osu-performance` due to https://github.com/ppy/osu/pull/20558, but this isn't a huge deal for now I think?
I'm just doing this to remove the rounding that breaks compilation.
=> Update osu nuget packages

osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/SerialisationTests.cs
Also fixes an oversight when combining the test's startup logic.
=> Change production check to be portable

osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayTimeProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.sln.DotSettings, osu.Server.Queues.ScoreStatisticsProcessor/LegacyDatabaseHelper.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/Medal.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/IMedalAwarder.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/PackMedalAwarder.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalProcessor.cs
PRing ahead of adding proper testability (currently looking at updating tests to user a more portable means).
Currently only processes a minimal subset of medals, but is designed to be modular and performant enough to handle all existing medals.
=> Add medal processor

osu.Server.Queues.ScorePump/Queue/ImportHighScores.cs, osu.Server.Queues.ScorePump/Queue/UpgradeScores.cs, osu.Server.Queues.ScorePump/Queue/WatchNewScores.cs
Turns out that without this, things are completely broken since partitioning was added. This is because, as an optimisation, MySQL will return all results from one partition before the next by default. Which meant that these iteration commands would only see `preserve=0` scores.
=> Add missing `ORDER BY` syntax to `solo_scores` pagination

osu.Server.Queues.ScorePump/Queue/ImportHighScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs, osu.Server.Queues.ScoreStatisticsProcessor/ElasticQueueProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsProcessor.cs
I was originally going to write this as a separate command... but it turns out that it's probably lower effort on all parts to reuse this existing command. Abstracting out the shared parts to a base class was a bit of a pain.
I've tested this locally and it seems to work quite well:
https://user-images.githubusercontent.com/191335/205884294-f76f02ba-2835-4511-9801-253d54bcd096.mp4
=> Add support for realtime legacy score importing (and automatic indexing)

UseLocalQueueProcessor.ps1, UseLocalQueueProcessor.sh
Just happened to need these for some experimentation, so I figured I'd PR them.
They can obviously go on any other queue processor as well but I'm not doing that right now.
=> Add local checkout scripts for `osu-queue-processor`

osu.Server.Queues.ScorePump/osu.Server.Queues.ScorePump.csproj, osu.Server.Queues.ScoreStatisticsProcessor/Models/Messages/ScoreProcessed.cs, osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Step two to the [proposed flow](https://github.com/ppy/osu/issues/18877#issuecomment-1356880170) required for https://github.com/ppy/osu/issues/18877.
Not much to see here either, but please do advise on data structure design, naming conventions, and error handling. I've made educated guesses but they may well turn out to be incorrect.
Notably, the amount of data in the published message is minimal, placing the burden of refetching the updated user statistics on the subscribers. This feels more versatile but also possibly inconvenient.
=> Publish messages about score processing completion to redis

osu.Server.Queues.ScorePump/Performance/PerformanceCommand.cs
Not sure why this is the case, but it's weird.
=> Allow reprocessing performance totals of users even when existing pp is zero

.config/dotnet-tools.json, osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
While investigating [reports of pp totals not updating](https://github.com/ppy/osu/discussions/22728#discussioncomment-5274115) I noticed that new builds may no be picked up for total calculations.
The fix is a very naive method of refreshing the build/blacklist cache.
I chose 1 minute to generally give it enough time to revalidate cache before someone was to complete a beatmap on a new release. We could potentially make this longer (or smarter) in the future if required.
=> Fix build cache never being updated until server restart

osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs, osu.Server.Queues.ScoreStatisticsProcessor/Stores/BeatmapStore.cs, osu.Server.Queues.ScoreStatisticsProcessor/StreamedWorkingBeatmap.cs
In order to try to resolve https://github.com/ppy/osu/issues/21815, I want to try out performing realtime difficulty calculation to see where bottlenecks appear.
This PR adds two environment variables:
- `BEATMAP_DOWNLOAD_PATH` : Set this to the `osu` file download path. Defaults to `https://osu.ppy.sh/osu/{0}`.
Of particular importance, `BEATMAP_DOWNLOAD_PATH` should be set to a path that isn't rate-limited, similar to what is done for `osu-difficulty-calculator` and `osu-beatmap-difficulty-lookup-cache`.
**This PR contains no caching** - please advise on whether/how I should consider some form of minimal caching, perhaps at a `WorkingBeatmap` level, though I'm not sure how useful it'll be if the general case is players playing a very wide range of beatmaps.
**I have not considered full …
=> Add option to use realtime difficulty calculation

osu.Server.Queues.ScorePump/Queue/ImportHighScoresCommand.cs, osu.Server.Queues.ScorePump/RecalculateScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/StreamedWorkingBeatmap.cs, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Prereqs:
One questionable/important aspect is that we don't store difficulty attributes for _all_ mod combinations. For example, for +HDHR, we only store the difficulty attributes for +HR. Because of this, there's an extra step here that re-multiplies the `LegacyComboScore` with the correct mod multiplier.  
This could result in an off-by-one score for each hitobject because [legacy scoring truncates at every judgement](https://github.com/ppy/osu/pull/24072/files#diff-c39a8a7ee2d48bcf35309f47a10b371f662af92a1b7638a0f7320d31591fa8edR162), that adds up over time. For example, [chocomint's score on `FREEDOM DiVE [FOUR DIMENSIONS]`](https://osu.ppy.sh/scores/osu/2177560145) converts to `1116538` when imported via this process, but `1116540` when imported directly from replay into lazer.
I've …
=> Convert legacy total score to standardised when importing high scores

osu.Server.Queues.ScoreStatisticsProcessor/Models/Beatmap.cs
These were recently changed to be `MEDIUMINT UNSIGNED` in the database, which causes errors such as:
```
20963-ppcalc-1  | Unhandled exception. System.Data.DataException: Error parsing column 8 (countTotal=63962 - UInt32)
20963-ppcalc-1  |  ---> System.OverflowException: Arithmetic operation resulted in an overflow.
20963-ppcalc-1  |    at Deserializecf30c795-010e-4dbf-bb01-ce4cdfb1cf4b(IDataReader )
20963-ppcalc-1  |    --- End of inner exception stack trace ---
20963-ppcalc-1  |    at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3706
20963-ppcalc-1  |    at Deserializecf30c795-010e-4dbf-bb01-ce4cdfb1cf4b(IDataReader )
20963-ppcalc-1  |    at Dapper.SqlMapper.QueryRowAsync[T](IDbConnection cnn, Row row, …
```
=> Fix beatmap object counts data type

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/DeleteNonPreservedScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/MaintenanceCommands.cs, osu.Server.Queues.ScoreStatisticsProcessor/Program.cs
Note that cancellation doesn't work because dapper. Will probably want to consider migrating to something that does work.
I'm not aiming for efficiency here because it doesn't need to be that efficient. Currently running on production to test (is cleaning around 500 scores per second).
Addresses part of https://github.com/ppy/osu-queue-score-statistics/issues/141 (deleting of scores which are already in a non-preserved state). Remaining piece is to downgrade preserved scores to non-preserved when they can be.
=> Add command to clean up non-preserved scores

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/MarkNonPreservedScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/MaintenanceCommands.cs
This is a first step implementation which runs across all users.
The next step is making a queue for this, so that processes like score submission, pinning/unpinning etc. can notify us that we need to re-check a user. This should reduce the overhead involved in this process.
I've already structured this code in a way it can be extracted out for the next step, so this is mainly to get eyes on the process and have a fallback maintenance command for when shit-hits-fan.
=> Add command to revoke preserved flag from scores which no longer require it

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
RFC at best. Will need to backport this to an older release and test before it's ready for review.
=> Add ability to re-run score imports and update existing items

osu.Server.Queues.ScoreStatisticsProcessor.sln.DotSettings, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/DeleteImportedHighScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/QueueCommands.cs
I wrote this, but realised we can probably benefit more from a command which re-imports "in-place", keeping the same ID mapping. So I'm going to make that now in addition to this.
But might as well have this one handy for that one rainy day when shit hits the fan?
Closes #146.
Note that this hasn't been heavily battle-tested.
=> Add command to delete imported high scores

osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/SerialisationTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/DeleteNonPreservedScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/MarkNonPreservedScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/DeleteImportedHighScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/PumpAllScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/Beatmap.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/BeatmapDifficultyAttribute.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/BeatmapSet.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/Build.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/PerformanceBlacklistEntry.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/ProcessHistory.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScore.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScoreLegacyIDMap.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScorePerformance.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MaxComboProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/PackMedalAwarder.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Stores/BeatmapStore.cs, osu.Server.Queues.ScoreStatisticsProcessor/Stores/BuildStore.cs, osu.Server.Queues.ScoreStatisticsProcessor/Stores/StreamedWorkingBeatmap.cs
Rider can't understand these constants, which makes database introspection quite useless. Also I don't think it's making things any clearer having the constants.
=> Replace all usage of `TABLE_NAME` constants with direct table names

osu.Server.Queues.ScoreStatisticsProcessor/Program.cs
I have a bash script with `set -e`, and I expect it to error out immediately if one of these commands fails. Currently it doesn't do so if the failure is as a result of a change of arguments. Or a non-zero return by commands, but we don't really do that I think (exceptions set error code to 134 - `SIGABRT`).
Master:
```
$ dotnet run -- wangs
Specify --help for a list of available options and commands.
Unrecognized command or argument 'wangs'
$ echo $?
0
```
PR:
```
$ dotnet run -- wangs
Specify --help for a list of available options and commands.
Unrecognized command or argument 'wangs'
$ echo $?
1
```
=> Fix error code on unknown argument

osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/UserRankCountProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserRankCountProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs
Closes #133.
As per [discord conversation](https://discord.com/channels/188630481301012481/188630652340404224/1146035221628731423), basically written with zero regard for performance, only correctness of behaviour. There are probably places that are going to hurt in this implementation.
Notably, this implementation relies on there being an absolute ordering of scores from a given user on a given beatmap in a given ruleset, to determine which score to pick as the "source" of rank to tally. The criteria chosen are: total score descending, then ID descending (as a substitute for "newest") as a tie-breaker.
[I brought that up on discord too](https://discord.com/channels/188630481301012481/188630652340404224/1146055765107421254), and there were two alternatives offered for the tie-breaker: …
=> Add support for increasing rank counts

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/MigratePlaylistScoresToSoloScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/MaintenanceCommands.cs
This is to be used to preserve ongoing featured artist / spotlight room's scores as we migrate scores to the new table.
It means we can continue to move forward without worrying about breaking things, basically.
It's made to only run for playlists, and not migrate *all* scores, but could be expanded in the future if we want to have more coverage.
=> Add command to migrate playlist scores from `multiplayer_scores` to `solo_scores`

osu.Server.Queues.ScoreStatisticsProcessor.Tests/osu.Server.Queues.ScoreStatisticsProcessor.Tests.csproj, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/BeatmapScoringAttributes.cs, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
=> Read scoring attributes from the new table

osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/TotalScoreProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/TotalScoreProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Stores/BeatmapStore.cs, osu.Server.Queues.ScoreStatisticsProcessor/Stores/BuildStore.cs, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
As per https://github.com/ppy/osu-queue-score-statistics/issues/134#issuecomment-1686230928
=> Use classic score in total score processor

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/MigratePlaylistScoresToSoloScoresCommand.cs
Already running on production
- Add support for migrating all playlists to new table structure
- Move insert command preparation outside of loop for better performance
- Update `scores_high` table with link IDs
- Allow cancellation at more opportunities
- Use more efficient lookup for query
=> Migration attempt 2

osu.Server.Queues.ScoreStatisticsProcessor.Tests/RankedScoreProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/UserRankCountProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Helpers/DatabaseHelper.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/RankedScoreProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserRankCountProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs
- Closes https://github.com/ppy/osu-queue-score-statistics/issues/134
Not much to say here really. A lot of this implementation is copy-paste from the rank count processor, with the exception of having to check the beatmap status. [Wiki says](https://osu.ppy.sh/wiki/en/Gameplay/Score/Ranked_score) ranked, loved, and approved count; that information comes from https://github.com/ppy/osu-wiki/pull/8488, which had @peppy reviewing, so seems legit.
The other part I wasn't 100% on here when querying the beatmap status, is whether to go for a local query or reuse `BeatmapStore` instead to leverage caching. Ended up doing a local query in the end as it seemed less overkill, but can switch back to the cache if you decide that's better.
=> Add support for increasing ranked score

osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
As of https://github.com/ppy/osu/pull/24640, NC no longer inherits DT and DC no longer inherits HT.
This can be merged as is without an update to nuget packages.
=> Explicitly specify NC/DC as mods valid for PP

osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayCountProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs
Covers `osu_counts` playcount, as well as beatmap and beatmap set level playcounts. All implemented using the same logic that as web-10.
personal reminder: consider backfilling these fields from solo_scores when deploying.
=> Add support for incrementing global and beatmap playcounts

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
Should address https://github.com/ppy/osu/discussions/25397 (going forward, not existing scores; they will need to be manually fixed or we should just wait until re-importing everything).
Of note, this only works if we assume there is one single instance of `osu-performance` running (so processing is in a consistent incrementing fashion), else we may skip ahead with the `lastId = Max()` logic. But we haven't run multiple `osu-performance` instances in years so it's probably okay?
If we want to support the above case better, the checks would need to be moved out of the SQL query and into actual logic, incrementing `lastId` only to the last processed row, and reprocessing that batch until all are satisfied. Personally don't think it's worth it.
Note that I haven't tested this yet, but it's …
=> Ensure `pp` is populated before attempting to import a legacy score

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
When running the diffcalc sheet generator (e.g. https://github.com/ppy/osu/actions/runs/7019346258/job/19096638966), I noticed that it would get stuck querying only 1000 scores / sec, which is the default amount when not checking slave latency.
=> Always query maximum amount when not checking slave latency

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
Since https://github.com/ppy/osu-queue-score-statistics/pull/173, the importer uses the maximum number of scores per query if slave latency isn't checked. This just about reaches the default [maximum connection pool size](https://dev.mysql.com/doc/connector-net/en/connector-net-8-0-connection-options.html) (Ctrl+F 'MaximumPoolsize') and crashes: https://github.com/ppy/osu/actions/runs/7030178231/job/19129260473
By reducing this value to 40000, we have about 20 extra connections to play around with, without having to change the connection string.
=> Reduce maximum number of scores per query

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
While working through the import process today to ensure we have everything covered, I realised that the previous fix I made for  ensuring scores are processed was insufficient due to the `null` allowance. Because score submission in web-10 is not done within a transaction, there's a window of time where rows are in `osu_scores_high` but not in `score_process_queue`.
To resolve this, we need to assume two modes of operation:
- Batch processing, when `StartId` is non-null, which will now process from the specified ID up to the last entry in `osu_scores_high` which doesn't have a `score_process_queue` entry (generally two days before current time, due to partition cycling).
- Live mode, when `StartId` is null, which will now process only entries with a `score_process_queue` entry.
I haven't …
=> Remove any chance of incorrect score handling due to missing entries in `score_process_queue`

osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/DeleteImportedHighScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Since we're not sure yet on the implementation of the mechanics of this mod (e.g. https://github.com/ppy/osu/issues/11769), it's easiest to just not allow it to be ranked for now. Scores coming from stable are still allowed to give PP.
=> Disallow classic mod from giving PP (for now)

osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/TotalScoreProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/IProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/HitStatisticsProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MaxComboProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayTimeProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/RankedScoreProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/TotalScoreProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserRankCountProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs
Aims to resolve https://github.com/ppy/osu-infrastructure/issues/25.
This PR allows a limited subset of PP-related processors to run for legacy scores, and changes the score import job to push imported scores for aforementioned processing when running in watch/indefinite mode.
I am very intentionally opening this as draft to first ensure that I am in the correct wheelhouse when it comes to what the issue above intended to convey. **Therefore, this is extremely untested code. It passes tests, but that means nothing for the import job. I have not attempted to run the import job. It only works in my head. Please give this a quick general review, but please do not merge this until I have tested it.**
I **will** attempt to run it and test it, to the best of my ability, using ad-hoc means, …
=> Allow limited processing of imported high scores

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
Until now it was very hard to figure out which score actually caused the failure, especially running against `data.ppy.sh` test data where the range of each batch can be 30 mil scores (due to holes between each score).
Tested using:
```diff
diff --git a/osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs b/osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
index 42d6c45..c47f5e4 100644
--- a/osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
+++ b/osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
@@ -559,6 +559,9 @@ namespace osu.Server.Queues.ScoreStatisticsProcessor.Commands.Queue
DefaultValueHandling = DefaultValueHandling.Ignore
});
+ …
```
=> Output legacy `score_id` when a processing failure happens

osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
- We noticed there are already scores in the database that have been set with lazer that don't have a `build_id`. I previously had a condition for this, that was changed to an assert following discussion, that actually cannot be asserted.
- Some scores present in the database may already have PP values from before we had per-mod filtering for PP (e.g. RX scores or such). These should not be considered towards the user total.
=> Add more PP safeguards

osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayCountProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayTimeProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Helpers/PlayValidityHelper.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayTimeProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs
Closes https://github.com/ppy/osu-queue-score-statistics/issues/63.
- The length of play condition was taken directly from https://github.com/ppy/osu-queue-score-statistics/issues/63#issuecomment-1202043145.
- The total score condition was adapted from the above but reduced, as it will be operating on standardised score rather than score V1, so 10k would be generally more punishing than in stable.
- There is also a total hit count condition as suggested in https://github.com/ppy/osu-queue-score-statistics/issues/63#issuecomment-1202040431. Potentially removable, I'm up for discussing the validity of it.
For reference:
=> Only increment playcount & play time if score is considered valid for it

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/HighScore.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ScoreProcessQueue.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/WatchHighScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/QueueCommands.cs
Posting this for review, but I'l be testing this live immediately.
Basically, this adds a new watch mode command. The old one still exists and can still watch, but the new one handles things in a slightly better way:
- The source of new scores is now tailing `score_process_queue` rather than `osu_scores_high`. This was done to make us aware of deletions performed by web-10 (which are inserted into the queue table with `is_deletion = true`.
- All batching is removed to simplify things as much as possible. For the watch mode we don't need any kind of insane performance, so I cut things back to the basics.
- All slave checks and rate adjusts are removed for the same reason.
- Deleting rows is now supported by `BatchInserter`. Note that this will only take effect with the new watch mode …
=> Add new watch mode command

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/HighScore.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/WatchHighScoresCommand.cs
Simplest fix for now. Has been deployed a couple of days and is running well.
=> Fix some entries not waiting for performance population before importing

osu.Server.Queues.ScoreStatisticsProcessor/Processors/RankedScoreProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserRankCountProcessor.cs
These just make it confusing to follow, and reduce confidence in the
"RunOnFailedScores" flag.
=> Remove redundant `score.Passed` checks

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/HighScore.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/WatchHighScoresCommand.cs
Primary goal: avoid table fragmentation from having 80 threads inserting at once.
Secondary goal: improve performance when running in single thread mode.
Can now insert consistently at 8.4k rows/second with one thread. Increasing threads now results in insane performance (4 threads can reach 16k rows/second), but the higher you go, the more table fragmentation you incur. Might still be useful for CI etc. though. Might need tuning if we want to push threads too high as it currently consumed a lot of mysql connections when populating beatmap attribute caches.
Have not tested watch mode yet. Just PRing for initial visibility, as always, already testing on production.
=> Refactor to avoid fragmentation

osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/UserStats.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
This switches away from the "experimental" or "pp^next" to the true pp value.
=> Point user performance processor to update final pp value

osu.Server.Queues.ScoreStatisticsProcessor.Tests/osu.Server.Queues.ScoreStatisticsProcessor.Tests.csproj, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyImportedScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
- Will close https://github.com/ppy/osu/issues/26595
~~**Caution: This is very untested.** It only works in my head. I would test but right now my box is working as a heater doing diffcalc spreadsheets, and I'd rather not push my luck and have it hang on me. I'm PRing early for visibility and for visibility alone. And testing convenience I guess since I will want to run score sheets using this diff to verify that I didn't break anything.~~
As requested in https://github.com/ppy/osu/issues/26595#issuecomment-1903767921, this includes a rank check in the verify command from https://github.com/ppy/osu-queue-score-statistics/commit/68e53cda1583d44ec0466ba23a69348eb93edeba. But with fixes around quoting the `rank` column name (and actually selecting it from DB).
=> Use updated accuracy & grade definitions when importing stable scores

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/HighScore.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/WatchScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/QueueCommands.cs
Until now, `osu_scores` table has been used to show "recent plays" on user profiles. This doesn't contain lazer scores.
To allow osu-web to read from only a single source of truth (the new `scores` table) we must import these scores from the old tables.
This watcher handles that process. It's written to be as simple as possible to get this out for the initial launch.
- This only handles non-high-scores. To make this work, there's a 5 second delay applied, to ensure that the `high_score_id` column has been populated by `osu-web-10` (it doesn't guard the insertion into `osu_scores` and `osu_scores_high` with a transaction, so this is best-effort).
- There's no gap / resume / whatever support. If this isn't running, scores are just not imported. These scores are throwaway (they get partition …
=> Add command to watch non-high-scores

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/WatchScoresCommand.cs
All failed scores are failing right now in osu! mode.
This is just a workaround until we fix the underlying issue.
Tracking at https://github.com/ppy/osu-queue-score-statistics/issues/209
=> Don't throw on failure to convert scores

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyImportedScoresCommand.cs
Unfortunately requires to be per-ruleset now, but can run much faster. At least in delete mode.
=> Make verify command faster by bypassing second-level data lookup

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/WatchHighScoresCommand.cs
Probably never going to actually be an issue, but this is more correct. Basically as there's no transaction around the score and queue insert during web-10 score submission, two submissions could execute in a different ordering. We should preserve `score_id` ordering as much as possible.
=> Order by `score_id` instead of `queue_id`

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/WatchHighScoresCommand.cs
This has happened twice now, where a score in the queue table ends up stuck in a `status=0` state.
I'm not yet sure why this happens, but given how rare it is my primary goal is to just keep things running so they don't need manual intervention. (and we already have verification procedures to amend incorrect pp should it actually be visible to a user).
=> Add a timeout condition to avoid score watchers getting stuck

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs
Noticed during last run. Maybe adds small overhead but probably fine.
=> Fix `BatchInserter` not showing correct process range due to no guaranteed ordering

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyImportedScoresCommand.cs
I'd been meaning to do this for a while now, in order to allow rewriting ranks to the correct equations, something I've not been able to do due to the overhead of individual SQL writes in this command.
I already have this stabilised and running on production, updating around 3,000 rows per second (ample for this kind of operation).
=> Change verify command to support batched writes

.config/dotnet-tools.json, .github/workflows/ci.yml, osu.Server.Queues.ScoreStatisticsProcessor.Tests/osu.Server.Queues.ScoreStatisticsProcessor.Tests.csproj, osu.Server.Queues.ScoreStatisticsProcessor.sln.DotSettings, osu.Server.Queues.ScoreStatisticsProcessor/Dockerfile, osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Note classic mod carve-out. This is [covered by tests](https://github.com/ppy/osu-queue-score-statistics/blob/2264bfa68e14bb16ec71a7cac2072bdcfaf565b6/osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs#L231-L241).
=> Use reintroduced `IMod.Ranked` property from game to determine eligibility of score for pp

.github/workflows/ci.yml, .github/workflows/pack.yml
Relevant bumps:
- https://github.com/actions/checkout/releases/tag/v4.0.0
- https://github.com/actions/setup-dotnet/releases/tag/v4.0.0
- https://github.com/docker/metadata-action/releases/tag/v5.0.0
- https://github.com/docker/setup-buildx-action/releases/tag/v3.0.0
- https://github.com/docker/login-action/releases/tag/v3.0.0
- https://github.com/docker/build-push-action/releases/tag/v5.0.0
- Caveats similar to https://github.com/ppy/osu-server-spectator/pull/221 apply.
- https://github.com/peter-evans/repository-dispatch/releases/tag/v3.0.0
=> Update github actions to resolve deprecation warnings

osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
We use this flag for cases where scores should not be considered for PP or leaderboards now. Cases where PP is not required simply leaves it as null.
=> Stop marking scores as `ranked = 0` for pp only purposes

osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayCountProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs
Intends to fix https://github.com/ppy/osu/issues/27485 for new incoming scores. I don't know what happens to existing scores. Is there a tool that can recompute these already maybe?
As far as I can tell the implementation of this should match `osu-web-10`. It makes *some* sense to me when I squint at it, but I'm not super sure.
=> Fix play count processor not incrementing pass count

osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/PackMedalAwarder.cs
The fact that *this* awarder is the one with the most issues despite being in source for months now is ironic.
As far as I can tell `passed = 1` is the only viable condition here? `ranked = 0` seems useless although I'm not sure what that flag means anymore (I think its goal is now to be set to 0 when a map exits qualified, and most maps in packs are ranked already?) and I'm not sure `preserved = 1` is doing anything right now?
I'm not sure if the indices are able to support this query. Probably needs a safety check.
=> Fix failed plays being included in pack medal query

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/HighScore.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/WatchHighScoresCommand.cs
Score pins generally mark scores as `preserve=1` and therefore can be pinned indefinitely, but for the time being, the legacy score importer is forcefully (hard) deleting scores when they are beaten so that the stored scores match the old tables 1:1. So, let's nuke pinned scores along with the scores themselves to keep parity.
=> Delete score pins when cleaning up old user high scores during high score import

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/DeleteNonPreservedScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/MigratedSoloScoresToScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/MaintenanceCommands.cs
This was used to resolve https://github.com/ppy/osu-web/issues/10725. It has already been run on production, and any issues were ironed out.
I'm PRing this because the code will likely be used again in the near future for other similar cases, with different source queries. I'm not overthinking the flexibility of this – will just edit the query as required when it comes up.
=> Add command for migration of `solo_scores` to `scores`

osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Helpers/LegacyDatabaseHelper.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
- Closes https://github.com/ppy/osu-web/issues/10937
I believe this to be a straight port of the correspondent `osu-web-10` logic, but please do double-check the logic, especially around the 90-day history handling since there's some implicit understanding on how that works that I basically inferred backwards from `osu-web` and `osu-web-10` source.
May be best to deploy after https://github.com/ppy/osu/issues/27174 is resolved.
=> Update user highest rank & rolling rank history

osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/PerformanceCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/UpdateUserTotalsCommands.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/UserTotals/UpdateUserTotalsFromSqlCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
Will be used for an initial run to update total PPs to new algorithm.
Previous runs would do batch reprocessing via `osu-performance` using something like:
```bash
./osu-performance sql "select user_id from osu_user_stats where rank_score > 0 and last_played > '2021-01-14' order by rank_score asc" -m osu
```
Of note, see commit message of [ea09969](https://github.com/ppy/osu-queue-score-statistics/pull/239/commits/ea099693b5aa75e50f64e56269caeb81fc032fc1) for reasoning for not updating some pieces.
=> Add command to process total PP for users based on sql

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs
If a score to be batch-inserted had no associated insertion SQL (e.g. due to being deleted), it would get skipped when assembling the full batch SQL insertion statement - however it would continue to remain in the `scores` array, which is important since statements lower down implicitly assume that all scores from the array have actually been inserted (by using `LAST_INSERT_ID()` from mysql and offsetting it by `scores.Length - 1`).
To avoid this scenario, drop such items from the array entirely prior to the insertion.
=> Fix possible overestimation of inserted row count in batch inserter

osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/RankMilestoneMedalAwarder.cs
Closes https://github.com/ppy/osu/issues/27581.
I did mention this wasn't implemented in https://github.com/ppy/osu-queue-score-statistics/pull/195#issuecomment-1944403240, but it was a long PR thread so it might have gotten missed.
~~Not sure if this should be merged imminently while the yo-yo effect with ranks shifting because of the bonus pp discrepancy is still ongoing.~~ I believe this should no longer be a concern.
=> Implement rank milestone medals

osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
A test added in https://github.com/ppy/osu-queue-score-statistics/pull/212, which was supposed to exercise the queue processor writing pp values back to legacy `scores_high` tables, [is currently failing on master](https://github.com/ppy/osu-queue-score-statistics/actions/runs/8370540426/job/22918071187).
The direct reason why is that `ScorePerformanceProcessor` is currently disabled for legacy scores as per https://github.com/ppy/osu-queue-score-statistics/pull/212#issuecomment-2011297448. This was required by https://github.com/ppy/osu-queue-score-statistics/pull/239.
The _indirect_ reason why this happened is that I cannot see CI test runs on _any_ of the commits authored by @tsunyoku in the PR, so there were never any tests run _to fail_. I'm not sure where _that_ comes from. May have …
=> Fix failing test

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/DeleteNonPreservedScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyReplayExistsCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Helpers/S3.cs
One of the pending items in https://github.com/ppy/osu-queue-score-statistics/issues/141.
Tested against a real S3 bucket, seems to work.
=> Delete replays from S3 when cleaning up non-preserved scores

osu.Server.Queues.ScoreStatisticsProcessor.Tests/ManiaKeyModeUserStatsProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Helpers/UserTotalPerformanceAggregateHelper.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/UserStatsManiaKeyCount.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/ManiaKeyModeUserStatsProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
- Closes https://github.com/ppy/osu-web/issues/11026
- Intends to obsolete https://github.com/ppy/osu-queue-mania-key-rank-processor
RFC. The logic is more or less a straight port of the old processor, and things appear to work in my testing, but at least all of the queries need a cross-check to determine whether they're going to obliterate mysql on the new table.
The intention is that when this gets deployed, `osu-queue-mania-key-rank-processor` can be turned off, `osu-web-10` can stop pushing to the `osu-queue:mania4k7k` queue, and then we can delete said queue at the end of it all. That is why I made this run on legacy scores too.
=> Add processor for mania keymode user stats

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/MarkNonPreservedScoresCommand.cs
Another item from https://github.com/ppy/osu-queue-score-statistics/issues/141.
I'd like to think that the query should be for all intents and purposes tolerable, given that it's just a lookup on primary key?
```
MySQL [osu]> DESCRIBE multiplayer_playlist_item_scores;
+------------------+-----------------+------+-----+---------+-------+
| Field            | Type            | Null | Key | Default | Extra |
+------------------+-----------------+------+-----+---------+-------+
| user_id          | int unsigned    | NO   | MUL | NULL    |       |
| playlist_item_id | bigint unsigned | NO   | MUL | NULL    |       |
| score_id         | bigint unsigned | NO   | PRI | NULL    |       |
+------------------+-----------------+------+-----+---------+-------+
```
=> Check for multiplayer usage of score before marking it as non-preserved

osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalAwarderTest.cs
This is a little annoying - if you attempt to call `AddBeatmap()` multiple times with the same set ID with the intention of creating a multi-difficulty beatmap set, it'll fail due to a duplicate primary key.
Dapper type mapping nonsense [strikes again](https://github.com/ppy/osu-queue-score-statistics/commit/26bcebd0c7898c44074192fba82b49ec0c723d29) (scores would have numbers instead of letter ranks after insertions).
This only becomes apparent when querying the database directly rather than relying on dapper _un_-mapping.
For use _elsewhere_.
=> Fix some test-specific issues

osu.Server.Queues.ScoreStatisticsProcessor.Tests/LastPlayedDateProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/LastPlayedDateProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs
Not sure how widely used this is exactly, but `osu-web-10` updates this during submission.
=> Add processor to update last played date in user stats table

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/ReindexBeatmapCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/ReorderIncorrectlyImportedTiedScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/MaintenanceCommands.cs
Will be used to close https://github.com/ppy/osu-web/issues/10922.
I've started to test this in production but the elastic indexing (or something in between) isn't working well, even though the IDs are correctly updating.
The case I ran this on already if you'd like to check on it:
before:
| score id   | legacy score id |
|------------|-----------------|
| [1961647015](https://osu.ppy.sh/scores/1961647015) | [214615400](https://osu.ppy.sh/scores/fruits/214615400) |
| [1961647016](https://osu.ppy.sh/scores/1961647016) | [214584096](https://osu.ppy.sh/scores/fruits/214584096) |
after:
| score id   | legacy score id |
|------------|-----------------|
| [1961647015](https://osu.ppy.sh/scores/1961647015) | [214584096](https://osu.ppy.sh/scores/fruits/214584096) |
| …
=> Add command to fix score ordering

.github/workflows/pack.yml
@peppy Manual approval for deployments to the `production` environment can be set up in this project's settings, similar to `osu-web`.
=> 👷 Trigger remote tag and build on private repo

osu.Server.Queues.ScoreStatisticsProcessor.Tests/ManiaKeyModeUserStatsProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/RankedScoreProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/UserRankCountProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Helpers/DatabaseHelper.cs
`DatabaseHelper.GetUserBestScoreFor()` did not check the value of `ranked` for the rows it was looking through to find the user's best score, which means that it could wrongly select an unranked score (i.e. one set back when a map was in qualified).
This potentially impacts: user total ranked score and user total letter rank counts in all rulesets (including mania keymodes). Please see added test cases for explanation as to how. The worst case scenario is that the user's real best score would not be counted towards those stats because of an unranked score with a higher total.
I don't believe there to be a sane path for retroactively fixing that (if it ever even happened, which I don't know - I only realised this could be a possibility when working on medals / …
=> Check ranked state when retrieving user best scores

osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalAwarderTest.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Helpers/MedalHelpers.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/Beatmap.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/BeatmapSet.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/ModIntroductionMedalAwarder.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/PackMedalAwarder.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/StarRatingMedalAwarder.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Stores/BeatmapStore.cs
The title of this PR is intentionally vague for _reasons_. This diff is a grab bag of various small changes I didn't want to open 8 separate PRs for. Recommend reviewing commits in isolation, although the full diff shouldn't be too bad either.
Most important commits first, least important last.
The `APIBeatmap` was already available under `Score`, so refetching it again appears to only incur extra database queries for zero benefit.
For future use elsewhere.
Note that this adds an extra query for retrieving the beatmap set for every score.
For future use elsewhere.
For future use elsewhere.
Just a straight-up test code quality improvement. This was extracted out to the superclass previously but must have returned following a botched merge or something.
For future use elsewhere.
Helpful …
=> General code quality improvements

osu.Server.Queues.ScoreStatisticsProcessor.Tests/MarkNonPreservedScoresCommandTest.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/MarkNonPreservedScoresCommand.cs
This came up yesterday - @peppy found a score with `ranked=0` and no corresponding `osu_scores_high` row, which ended up originating from a recently-ranked beatmap. `ranked=0` was [correctly set by osu-web](https://github.com/ppy/osu-web/blob/e1c3f5a907085d0b228ff848e956d34ec280cf95/app/Jobs/RemoveBeatmapsetSoloScores.php#L61), but the preserve command wasn't really even attempting to correctly account for it, which it should do now after 912b135eaf2440e62235740cac7a0454eaa6be56.
Note that this means that _every_ unranked score will be subject to non-preservation unless pinned and/or associated with a multiplayer room. This seems fine to me, but I'm not super sure it will be to everyone else.
Checking the ranked date was also brought up in related discussions but today I'm not really sure …
=> Check ranked state when determining user best score in mark non-preserved scores command

osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/ManiaKeyModeUserStatsProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Similar to what is done in web-10.
=> Add partition cache for `user_rank_index` updates

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyImportedScoresCommand.cs
The cursor trick doesn't work on docker/etc, making this command very spammy: https://github.com/ppy/osu/actions/runs/9298230620/job/25589772915
In this case, I'll set the `--quiet` flag and live with the single line of output at the end.
=> Reduce verbosity of `verify-imported-scores` command

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/PopulateTotalScoreWithoutModsCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/MaintenanceCommands.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScoreData.cs
- End goal is https://github.com/ppy/osu/issues/27685.
This PR ensures that the legacy score watchers populate `total_score_without_mods` correctly to the json (to match https://github.com/ppy/osu-web/pull/11211), and also features a command to fill in that data wherever it's missing, using an approximate estimate.
Only tested locally on a small `scores` table, so buyer beware.
=> Populate score without mods during ongoing imports & add command for backpopulation of it on existing scores

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyImportedScoresCommand.cs
This is still extremely noisy when running the diffcalc spreadsheet generator and makes logs unparseable.
=> Quieten more verify command output

osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Helpers/MedalHelpers.cs
Reported privately.
The corresponding web-10 query looks like this (somewhat abridged):
```sql
SELECT COUNT(*) FROM (
SELECT p.beatmapset_id FROM osu_beatmappacks_items p JOIN osu_beatmaps b USING (beatmapset_id) JOIN osu_scores_high s USING (beatmap_id) WHERE s.user_id = @userId AND b.playmode = 0 AND pack_id = @packId UNION DISTINCT
SELECT p.beatmapset_id FROM osu_beatmappacks_items p JOIN osu_beatmaps b USING (beatmapset_id) JOIN osu_scores_taiko_high s USING (beatmap_id) WHERE s.user_id = @userId AND b.playmode = 1 AND pack_id = @packId UNION DISTINCT
SELECT p.beatmapset_id FROM osu_beatmappacks_items p JOIN osu_beatmaps b USING (beatmapset_id) JOIN osu_scores_fruits_high s USING (beatmap_id) WHERE s.user_id = @userId AND b.playmode = 2 AND pack_id = @packId UNION DISTINCT
SELECT …
```
=> Fix pack pass check considering converted plays when pack is not associated with a ruleset

osu.Server.Queues.ScoreStatisticsProcessor.Tests/HitStatisticsProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/HitStatisticsProcessor.cs
Addresses https://github.com/ppy/osu/discussions/29328.
Readers could recall that [there is a set of helpers for this sort of thing game-side](https://github.com/ppy/osu/blob/ea94f903c1ef72ef79dff19d923fdbd4bfcf2357/osu.Game/Scoring/Legacy/ScoreInfoExtensions.cs#L67-L215) and then rightly ask why I'm not using that? Well, the answer is that this would be incorrect for mania.
What do I mean? While yes, using these helpers would correctly alias large tick hits to `count100` and small tick hits to `count50` in catch, it would also alias `HitResult.Perfect` to... `countGeki` in mania, and `HitResult.Good` to `countKatu`.
In mania specifically, web-10 would add `countGeki` to `count300` and `countKatu` to `count100` to account for this. Thus, a complete local copy of the relevant catch logic …
=> Count tick hits into hit/miss counts in catch plays

osu.Server.Queues.ScoreStatisticsProcessor/Helpers/LegacyDatabaseHelper.cs, osu.Server.Queues.ScoreStatisticsProcessor/Helpers/LegacyRulesetHelper.cs
These are used a *lot*, so this is quite a large saving. Mainly just aiming to get GC time down.
=> Use static ruleset classes rather than constructing on each usage

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/PerformanceCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateAllScoresByUserCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateAllScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/UpdateScoresCommands.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Stores/BeatmapStore.cs
This adds a new command which processes all scores in the database consecutively (based on primary key). This is more efficient for both reads and write due to the table's compression setting. In practice it's over a magnitude faster, and will replicate better.
In additions, this PR also:
- Adds better console output of the progress of ongoing operations
- Removes a stray `AsParallel()` call that didn't need to exist
- Allows cancellation during a single user processing
- Allows bypassing beatmap store refreshes for performance reasons
- Avoids database writes when the existing pp value is already correct-enough (within `0.1` as per [what the spreadsheet process currently checks for](https://discord.com/channels/90072389919997952/1083320217259749376/1296763588433674260))
Without database …
=> Score processing command updates for upcoming (and future PP deploys)

osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
cc @ThePooN we'll want to set this for dev environment deploys
`CLIENT_CHECK_VERSION=0` similar to osu-web.
=> Add environment variable to allow disabling client build checks

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateAllScoresCommand.cs
ProxySQL doesn't work great with this. If there's a pause (or sometimes even if there isn't) ie. connection may be dropped causing the reading to fail and abort the whole process.
I'm PRing this separately because I may bring this back in the near future, depending on how things go. Right now we're bottlenecked on writes, not reads, so it's not a huge issue.
Already using on production run.
=> Unapply non-buffered performance optimisation

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateAllScoresCommand.cs
A bit of a local optimisation for now.
Without:
```
caches: [beatmap 4,071 +42] [attrib 20,969 +110]
processed up to: 2430329 changed: 0 0.1% 37,869/s
```
With:
```
caches: [beatmap 4,071 +231] [attrib 20,956 +287]
processed up to: 2430329 changed: 0 0.1% 79,678/s
```
Also adds the ability to adjust settings on the fly.
FWIW I already looked into the mysql connector to make sure there's not a more efficient path to getting connections from a pool. There unfortunately doesn't seem to be. The overheads just get high at the rate of connections we're using (running with 96 threads at the moment for highest throughput).
=> Use manual connection pooling for score reprocessing

osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
This makes the insert totally disappear from my profiling, at least when running `TestNoReductionModsPackWithSelectedMods`.
Along with https://github.com/ppy/osu-queue-processor/pull/34, should bring CI run times back to where they were.
=> Batch attribute inserts into a single query

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/PerformanceCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateAllScoresByUserCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateScoresFromListCommand.cs
Some more optimisations I made in order to make updating user totals as a batch more efficient.
More details in some commit messages.
=> Improve throughput of other commands using `ProcessPartitioned` by allowing transaction and connection sharing

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateAllScoresCommand.cs
https://github.com/ppy/osu/actions/runs/11627419099/job/32380757841
```
2024-11-01T10:14:21.7694053Z ppcalc-1     | Processing all scores up to 3728268118, starting from 0
2024-11-01T10:14:21.7899436Z ppcalc-1     | Unhandled exception. System.InvalidOperationException: Cannot see if a key has been pressed when either application does not have a console or when console input has been redirected from a file. Try Console.In.Peek.
2024-11-01T10:14:21.7901136Z ppcalc-1     |    at System.Console.get_KeyAvailable()
2024-11-01T10:14:21.7903328Z ppcalc-1     |    at osu.Server.Queues.ScoreStatisticsProcessor.Commands.Performance.Scores.UpdateAllScoresCommand.handleInput() in /tmp/tmp.HkPQkGiFzg/osu-queue-score-statistics/osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/Updat …
```
=> Fix console on non-user-interactive sessions

osu.Server.Queues.ScoreStatisticsProcessor/Helpers/LegacyDatabaseHelper.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs
As [pointed out internally](https://discord.com/channels/90072389919997952/983550677794050108/1306327452364177418).
- `plain/text` is exactly backwards; [it's actually `text/plain`](https://developer.mozilla.org/en-US/docs/Web/HTTP/MIME_types#textplain).
- The MIME type spec is redundant there anyways. [`StringContent` implicitly means `text/plain` by default until specified otherwise.](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.stringcontent.-ctor?view=net-8.0#system-net-http-stringcontent-ctor(system-string))
- And the only place that used the `StringContent` path was wrong anyway, it was supposed to be doing `application/x-www-form-urlencoded`. [Which `FormUrlEncodedContent` is for, and is now used in the relevant …
=> Fix various content type issues on LIO request helpers

osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs
The check *works*, but it dies a little harder than it should. Selecting `*` when the type param in the `QueryFirstOrDefault<>()` invocation is `int?` is going to die, because dapper can't map 2 columns to one `int?`.
By chance this would work correctly on *non*-production databases, because if the row isn't there, then dapper just does the default part of `QueryFirstOrDefault<>()` which is `null`.
Also added quotes to the object names for safety.
Discovered when porting this to https://github.com/ppy/osu-server-beatmap-submission/pull/1.
=> Fix faulty production check in database test setup

osu.Server.Queues.ScoreStatisticsProcessor/Helpers/LegacyDatabaseHelper.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs
Follow up from https://github.com/ppy/osu-queue-score-statistics/pull/297
- Removed support for both `text/plain` (completely unnecessary ever, web can't do that) and `application/x-www-form-urlencoded` (web _can_ do that but why leave 2 formats in when 1 can work), leaving only `application/json`
- If the request is made with a null payload object, do not set `Content-Type`
=> Adjust LIO request helper further

README.md, osu.Server.Queues.ScoreStatisticsProcessor/Helpers/LegacyDatabaseHelper.cs
On several occasions, I've tried to test something involving LIO full-stack and forgot that the LIO helper hardcodes production. Thankfully I never did damage due to the interop secret check, but it's a bit bone-chilling every time. Additionally I believe this situation can't be correct as far as staging is involved, either.
The envvar is `LEGACY_IO_DOMAIN` (open to alternative naming suggestions). Same as the shared interop secret, this envvar is optional in debug (and it missing causes LIO to become a no-op), and required with no default and hard-fail on missing in release.
cc @ThePooN as requested (for presumed deployment config updates)
=> Split domain to which LIO requests are directed to envvar

osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserRankCountProcessor.cs
A step towards sanity, with a hope of resolving https://github.com/ppy/osu-web/issues/8443. Will be deployed alongside https://github.com/peppy/osu-web-10/commit/0233c980bd2f201448781068d842908c04a28e18.
=> Enable user rank processor on legacy scores

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyUserRankCounts.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/MaintenanceCommands.cs
Inspiration taken from [web-10 implementation](https://github.com/peppy/osu-web-10/blob/master/www/web/adm-fixrankcounts.php), but updated for the new scores table.
I haven't yet tested this (still have an ongoing processing queue which I don't want to run in parallel). Just PRing as I think it's mostly ready to go. I'll test it tomorrow and make any required amendments.
In conjunction with https://github.com/ppy/osu-queue-score-statistics/pull/303 (already deployed), closes https://github.com/ppy/osu-web/issues/8443.
=> Add command to fix non-matching rank counts

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyImportedScoresCommand.cs
Intended usage is to fix https://github.com/ppy/osu-web/issues/11697, after https://github.com/ppy/osu/pull/30917 is merged, deployed as part of `osu-difficulty-calculator`, and legacy scoring attributes are recomputed.
Explanation of the failure mode here that links `maximum_statistics` with the linked issue is in the OP of the issue.
I've tested this full-stack on my local osu-web instance, but probably best to exercise care.
=> Add capability to verify maximum statistics of scores

osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/IMedalAwarder.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/ModIntroductionMedalAwarder.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/PackMedalAwarder.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/RankMilestoneMedalAwarder.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/StarRatingMedalAwarder.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/StatisticsMedalAwarder.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalProcessor.cs
The goal of this change is to stop touching medal logic in osu-web-10, whether it be for any new medals going forward, or for fixes of existing medals that may have broken for one reason or another.
=> Allow medal awarders to process stable scores

osu.Server.Queues.ScoreStatisticsProcessor.Tests/DailySproutTest.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalAwarderTest.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/MonthlyShrubTest.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/WeeklySaplingTest.cs, osu.Server.Queues.ScoreStatisticsProcessor/Helpers/MedalHelpers.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/DailyChallengeMedalAwarder.cs
Closes https://github.com/ppy/osu-queue-score-statistics/issues/309.
See https://github.com/ppy/osu-queue-score-statistics/issues/309#issuecomment-2566205984 and further comments for discussion / rationale.
cc @Hiviexd @walavouchey
=> Disallow daily challenge-related medals from being awarded on non-daily-challenge score submissions

osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs, osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs
Closes https://github.com/ppy/osu-queue-score-statistics/issues/314.
Leaving logging so we have visibility if anything goes awry.
=> Stop marking preserve on new score arriving

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ProcessScoreCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/QueueCommands.cs, osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs
Intended use is to perform fixups when we find a bug. Or potentially to debug a scenario where we aren't sure what's going on and want to run a single score through the whole process for local evaluation.
=> Add command to reprocess a single score

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ProcessAllScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/PumpAllScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/QueueCommands.cs
Similar to `PumpAllScores` but without the queue.
Useful for local testing.
=> Add command to process all scores

osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScore.cs
See https://github.com/ppy/osu/pull/31595#discussion_r1923336441. Will confidently verify behaviour with a difficulty calculation sheet on the osu-side PR.
=> Pass `Difficulty` beatmap info property for `SoloScore` objects

osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateAllScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
It seems like this is occasionally failing, but due to exceptions being caught and logged to console, we have not seen an actual failure.
=> Stop catching exceptions in `ScorePerformanceProcessor`

osu.Server.Queues.ScoreStatisticsProcessor/Models/MedalAwarderContext.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/StarRatingMedalAwarder.cs
Since 2f603b7c22f6b53de53b4718394b96e8c562c053, difficulty attribute lookups no longer soft-fail if the rows are missing in the database, and instead hard-fail. In addition, from the latest star rating recalculation onward, only `approved > 0` beatmaps have difficulty attributes populated in the database.
This makes `MedalAwarderContext.BeatmapStore.GetDifficultyAttributesAsync()` unsafe, as medal processors (in particular, hush-hush ones) will attempt beatmap attribute lookups that may not necessarily hit *ranked* beatmaps, which will henceforth hard-fail rather than return `null` as previously.
To prevent this from happening, prevent medal awarders from being able to directly retrieve difficulty attributes via the beatmap store, and instead add a redirection method that does the …
=> Encapsulate difficulty attribute lookup logic in medal processing code to prevent invalid lookups

osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateAllScoresByUserCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateAllScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/MedalAwarderContext.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Stores/BeatmapStore.cs
This fixes the fact that we were instantiating one of these per scores processed, causing thousands of background pollers 🙈.
It also means the caches are now shared over multiple usages, which is beneficial.
=> Make `BeatmapStore` static

osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs
Some tests, especially medal-related, especially non-public ones, rely on being able to add difficulty attributes to the database, and don't really care about reuse of beatmap and beatmap set IDs between test fixtures (and rightly so). However, because the beatmap store is now assembly-static, this would lead to accidental test crosstalk wherein one test adding difficulty attributes for a beatmap would break another test elsewhere because of the caching layer and beatmap ID reuse.
The store cache purging was already being done, but only locally in a single test class.
=> Purge beatmap store caches on every test

osu.Server.Queues.ScoreStatisticsProcessor/Models/BeatmapSet.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserRankCountProcessor.cs
There have been many recurrent reports about user rank count totals going negative (such as
https://osu.ppy.sh/community/forums/topics/2076246?n=1). I've spent probably too much time trying to figure out how this is possible because it bothers me to no end. It doesn't appear to be anything from old web still being active and ruining things.
This temporary logging is supposed to maybe help me understand what's going on here. It's predicated on the fact that people keep reporting that this has something to do with playing qualified maps. Maybe if this collects enough data I might be able to establish some pattern of behaviour that causes this.
If you wish to test that this should detect the case I'm trying to detect, you can apply the following diff:
```diff
diff --git …
```
=> Log suspicious user rank count decrement operations to sentry

osu.Server.Queues.ScoreStatisticsProcessor/Helpers/DatabaseHelper.cs, osu.Server.Queues.ScoreStatisticsProcessor/Helpers/LegacyDatabaseHelper.cs, osu.Server.Queues.ScoreStatisticsProcessor/Helpers/WebRequestHelper.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/HighBeatmapLeaderboardRankEventEmitter.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
- Would close https://github.com/ppy/osu-web/issues/11188
PRing as draft because this is doing Weird Things (API calls to web to fetch the score's rank) because of the direction I was given internally and I want to make sure everyone is on board with the full implications of that.
The diff is a bit large because I got weirded out by the legacy interop request logic being in `DatabaseHelper` and I wanted to conjure a `WebHelper` anyway for handling of API.
I've tested the happy path once but not much else. Probably more testing around the token expiry logic is warranted, but I'll do that once I'm confident this diff doesn't get dumpstered on entry.
=> Emit lazer leaderboard rank events when processing lazer scores

osu.Server.Queues.ScoreStatisticsProcessor/Helpers/WebRequestHelper.cs
After deploying the latest changes whose aim is to emit high scoreboard rank events for lazer leaderboards, many systems started having a conniption around 00:00 UTC.
The likely explanation is that some job is running every day at midnight UTC, which causes `osu-web` to respond to API requests made by `osu-queue-score-statistics`  for scores with some delay, which - because of `osu-queue-score-statistics` performing the request inside a transaction - probably is bringing down everything else.
Performing web requests with a transaction held is suboptimal to say the least, but let's start with decreasing the timeout for now given that the rank achieved stuff is generally non-critical to the functioning of the game.
This timeout will also apply to LIO requests, which I think is probably fine …
=> Reduce web request timeouts

osu.Server.Queues.ScoreStatisticsProcessor.Tests/LegacyModsHelperTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Helpers/LegacyModsHelper.cs
Required as a result of https://github.com/ppy/osu/pull/31351.
Above change is a difficulty related change in the `pp-dev` branch, so this PR can be ignored until the next deploy cycle (where it will become a requirement).
=> Add Hidden as a relevant legacy mod for osu ruleset
