ppy/osu-queue-score-statistics

osu.Server.Queues.ScoreStatisticsProcessor/DifficultyAttributeExtensions.cs
As a result of https://github.com/ppy/osu/pull/14217. Requires nuget package update.
=> Add flashlight difficulty attribute

osu.Server.Queues.ScorePump/ImportHighScores.cs, osu.Server.Queues.ScorePump/Program.cs, osu.Server.Queues.ScorePump/PumpAllScores.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/osu.Server.Queues.ScoreStatisticsProcessor.Tests.csproj, osu.Server.Queues.ScoreStatisticsProcessor/LegacyDatabaseHelper.cs, osu.Server.Queues.ScoreStatisticsProcessor/LegacyRulesetHelper.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScore.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScoreInfo.cs, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
This is highly WIP, and shouldn't be merged before we discuss how to deal with the PKs and all.
It can be used for testing other score statistics processors as it is.
=> Add command to import osu_scores_high tables into solo_scores

osu.Server.Queues.ScorePump/ImportHighScores.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScoreInfo.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
In preparation for optimisations and larger changes to the surrounding code. Rationale for each change is in the respective commit message text.
=> Reduce populated data and tidy up population code

osu.Server.Queues.ScoreStatisticsProcessor/Processors/PerformanceProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
=> Apply osu!-side PerformanceCalculator changes

osu.Server.Queues.ScoreStatisticsProcessor.Tests/StatisticsUpdateTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MaxComboProcessor.cs
=> Don't count automation mods towards max combo

osu.Server.Queues.ScorePump/ImportHighScores.cs, osu.Server.Queues.ScorePump/Program.cs, osu.Server.Queues.ScorePump/osu.Server.Queues.ScorePump.csproj, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Have been running this in production. Better output, better startup throughputs (to avoid immediately overloading servers) and other fixes.
=> Various improvements to high score importer

osu.Server.Queues.ScoreStatisticsProcessor/LegacyDatabaseHelper.cs
=> Fix incorrect keys into osu_counts table

osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
=> Use new score processing methods in ScorePerformanceProcessor

osu.Server.Queues.ScoreStatisticsProcessor/IProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/LegacyDatabaseHelper.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsProcessor.cs
=> Add user total performance processing

osu.Server.Queues.ScoreStatisticsProcessor/Models/Build.cs, osu.Server.Queues.ScoreStatisticsProcessor/Stores/BuildStore.cs
Resolves https://github.com/ppy/osu-queue-score-statistics/issues/54
=> Filter `osu_builds` query to relevant builds

osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsProcessor.cs
Not yet tested, but should be fine.
=> Push scores to ES indexer queue after processing is complete

osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsProcessor.cs
Eventually this will be handled by osu-web I think. Already tested on production(tm).
=> Mark passed scores as preserve

osu.Server.Queues.ScoreStatisticsProcessor.Tests/StatisticsUpdateTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MaxComboProcessor.cs
We probably want the beatmap model populated at a higher level in the future, but working with what we have for now. Let's get osu-web pushing to this queue first and see how things play out from there (ppy/osu-web#9163).
Closes https://github.com/ppy/osu/issues/19576.
I'll fix existing cases manually once this is deployed.
=> Don't increase user max combo on non-ranked beatmaps

osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScore.cs
Removed in https://github.com/ppy/osu-web/pull/9170
=> Remove `deleted_at` from `SoloScore` model

osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsProcessor.cs
For consistency with https://github.com/ppy/osu-elastic-indexer/pull/128
Will need to be updated in production & staging, and also worth a tag after merge?
=> 🎨 Use uppercase SCHEMA env var for consistency

.config/dotnet-tools.json, .github/workflows/ci.yml
No testing for the time being (it's complicated), just build + code quality.
Example: https://github.com/smoogipoo/osu-queue-score-statistics/runs/8264603946?check_suite_focus=true
=> Add CI workflow

osu.Server.Queues.ScoreStatisticsProcessor/LegacyModsHelper.cs
=> Add TouchDevice mod combination

osu.Server.Queues.ScorePump/Queue/ImportHighScores.cs
Have tested in a production run of ~70m rows, seems to work as expected.
=> Cache all max combo lookups

.github/workflows/ci.yml, docker-compose.yml
=> Add basic `docker-compose` setup

osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/HitStatisticsProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/MaxComboProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayCountProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayTimeProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/TotalScoreProcessorTests.cs
=> Clean up `CancellationToken` handling

osu.Server.Queues.ScorePump/osu.Server.Queues.ScorePump.csproj, osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/HitStatisticsProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/MaxComboProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayCountProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayTimeProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/TotalScoreProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
See individual commit messages for more details.
=> Expose errors from queue processor during tests (and fix erroring tests)

osu.Server.Queues.ScoreStatisticsProcessor.Tests/AddBeatmapTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayTimeProcessorTests.cs
=> Various improvements to `AddBeatmap` method

.github/workflows/ci.yml, README.md, docker-compose.yml, osu.Server.Queues.ScorePump/osu.Server.Queues.ScorePump.csproj, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Also fixes a few issues that were experience in user testing
=> Add basic environment setup documentation

osu.Server.Queues.ScoreStatisticsProcessor.Tests/AddBeatmapTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/HitStatisticsProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/MaxComboProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayCountProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/TotalScoreProcessorTests.cs
Removes the weird try-catch-update flow. See individual commits.
=> Refactor beatmap adding to remove implicit default

osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalProcessor.cs
As expected, some sql statements are timing out so I think I'll temporarily turn this off.
=> Add ability to turn off medal awarding

osu.Server.Queues.ScorePump/Queue/ImportHighScoresCommand.cs
Fixes https://github.com/ppy/osu-web/issues/9681
=> Fix max combo missed during solo-score import

osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
=> Disallow PP for non-default rate adjustments

osu.Server.Queues.ScorePump/Queue/ClearQueueCommand.cs, osu.Server.Queues.ScorePump/Queue/PumpAllScoresCommand.cs, osu.Server.Queues.ScorePump/Queue/PumpTestDataCommand.cs, osu.Server.Queues.ScorePump/Queue/WatchNewScoresCommand.cs
Without this, cancellation just doesn't work how you would expect it to
=> Update all remaining commands to use `OnExecuteAsync` instead of `OnExecute`

README.md, osu.Server.Queues.ScoreStatisticsProcessor/Helpers/LegacyDatabaseHelper.cs
=> Document environment variables and rename env var for consistency

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
The fix here is to use an object that is a `class`, which can be nullable unlike a non-nullable tuple type. The latter is uglier to make work.
Context:
- I run this to import highscores to solo scores: https://github.com/smoogipoo/diffcalc-sheet-generator/blob/f0319ea34e27791091ab212ca690e9fa1c3db224/docker/importer/start.sh#L29-L38
- `SkipExisting` is true by default.
- Because it's an array of `(ulong, ulong)` which is non-nullable, the first condition `if ((existingMapping != null && skipExisting) ...` passes and the score is skipped.
=> Fix new highscores not being imported

osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/MaxComboProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/IProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/HitStatisticsProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/IMedalAwarder.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MaxComboProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/PackMedalAwarder.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayTimeProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/TotalScoreProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserRankCountProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs
See task list item in https://github.com/ppy/osu-infrastructure/issues/19
~~Not sure if any other processors need to be adjusted - just touching the PP processor for now.~~
=> Don't run certain processors for failed scores

osu.Server.Queues.ScoreStatisticsProcessor.Tests/TotalScoreProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/TotalScoreProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs
Intended to address concerns raised in https://github.com/ppy/osu-queue-score-statistics/pull/157#issuecomment-1748068167.
=> Properly handle multiple score algorithms when reverting total score

osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/MigratePlaylistScoresToSoloScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScore.cs
See https://github.com/tmsmith/Dapper-Extensions/issues/201.
Give up at this point.
=> Rewrite migrate playlists command to not use `InsertAsync`

osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/PlayCountProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs
=> Limit play count increases to only increment below a certain rate limit

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/WatchQueueCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs
```shell
> dotnet queue watch --disable MedalProcessor,RankedScoreProcessor
Active processors:
- HitStatisticsProcessor
- MaxComboProcessor
- PlayCountProcessor
- PlayTimeProcessor
- ScorePerformanceProcessor
- TotalScoreProcessor
- UserRankCountProcessor
- UserTotalPerformanceProcessor
Disabled processors:
- MedalProcessor
- RankedScoreProcessor
```
=> Add ability to disable any processor when watching a queue

osu.Server.Queues.ScoreStatisticsProcessor.Tests/TotalScoreProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/TotalScoreProcessor.cs
Closes https://github.com/ppy/osu-queue-score-statistics/issues/170.
=> Fix user level not being updated in database

osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScoreLegacyIDMap.cs
=> Fix legacy score ID column type

osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/MarkNonPreservedScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/DeleteImportedHighScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/ElasticQueueProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
- Add automatic schema support
- Remove unnecessary envvar set
=> Add support for automatic index schema lookup

osu.Server.Queues.ScoreStatisticsProcessor/Stores/BeatmapStore.cs
Which it currently is in production (and will continue to be in the foreseeable future).
Closes https://github.com/ppy/osu/issues/25719.
=> Fix Daycore mod not having an effect on pp values when realtime difficulty is off

osu.Server.Queues.ScoreStatisticsProcessor/Models/BeatmapScoringAttributes.cs, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Prereqs:
Works in-tandem with https://github.com/ppy/osu-difficulty-calculator/pull/228
=> Add new score attribute columns

README.md, osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/SerialisationTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/DeleteNonPreservedScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/MarkNonPreservedScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/MigratePlaylistScoresToSoloScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/DeleteImportedHighScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/PumpAllScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Helpers/DatabaseHelper.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/ProcessHistory.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScore.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScoreLegacyIDMap.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScorePerformance.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/PackMedalAwarder.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs
Basically locking in the current live build we have, and moving ahead towards the next release, so let's get this in `master`
=> Update table names

osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/SerialisationTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/MarkNonPreservedScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScore.cs, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Prereqs:
Fixes the issue brought up in https://github.com/ppy/osu/pull/25887#issuecomment-1864074315
=> Update total score/accuracy conversion to new paths

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs
This will let me run watch mode in the short term (until we decide to switch to the new processor a bit later on).
=> Add flag to allow skipping score-statistics-processor in watch mode

osu.Server.Queues.ScoreStatisticsProcessor.Tests/PerformanceProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Resolves https://github.com/ppy/osu-queue-score-statistics/issues/191
Prereqs:
Blanket applying for now.
=> Disallow giving PP for mods with non-default settings

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/DeleteImportedHighScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyImportedScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/MaintenanceCommands.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/HighScore.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/VerifyImportedScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/QueueCommands.cs
Just scoped to pp for now due to YESTERDAY'S CHAOS.
Running at about 1m rows per minute. ~36 hours for a full process.
=> Verify command

osu.Server.Queues.ScoreStatisticsProcessor.Tests/TotalScoreProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Helpers/PlayValidityHelper.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/TotalScoreProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsQueueProcessor.cs
Reported privately.
Condition lifted verbatim from previous implementation.
=> Do not count scores set on broken unranked beatmaps towards user total score

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/WatchHighScoresCommand.cs
Now that I'm running it... I found some issues 😅 .
Confirmed working well via deploy-to-production testing technique.
=> Fix some issues with watch mode

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyImportedScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/BatchInserter.cs
Testing in try run on production. Performance is limited to single thread but can easily be improved by threading.
=> Update verify scores command to handle total score and legacy total score

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyImportedScoresCommand.cs
This obviously doesn't fix the underlying cause, which I have half-fixed in legacy code (but will need to think more about a more robust fix).
I'm already testing this in production.
See https://github.com/orgs/ppy/projects/19/views/1?pane=issue&itemId=52355480 (targeted this immediately as a test for fixing using the command)
=> Add verification step for confirming replay flag is correct

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyReplayExistsCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/MaintenanceCommands.cs, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
A simple one. To be used hopefully once-ever, to fix https://github.com/orgs/ppy/projects/19/views/1?pane=issue&itemId=51932194.
https://github.com/orgs/ppy/projects/19/views/1?pane=issue&itemId=51932194
=> Add command to verify presence of replays on S3

osu.Server.Queues.ScoreStatisticsProcessor.Tests/DatabaseTest.cs, osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/PackMedalAwarder.cs
Temporary alternative to https://github.com/ppy/osu-queue-score-statistics/pull/233
=> Do not grant challenge pack medals for scores that don't grant pp

osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
Floating point inaccuracy could cause an off-by-one if we don't exclude ourselves from the query.
No test because hard to setup a test for this.
=> Never include self when querying for current rank

.github/workflows/pack.yml
Also disables private builds on suffixed tags.
Needs secret `DISCORD_INFRA_WEBHOOK_URL` added to this repository (identical from osu-web).
=> 👷 Add pending approval Discord notification

osu.Server.Queues.ScoreStatisticsProcessor.Tests/osu.Server.Queues.ScoreStatisticsProcessor.Tests.csproj, osu.Server.Queues.ScoreStatisticsProcessor/ElasticQueueProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
Pulls in https://github.com/ppy/osu/pull/27729#event-12243877951, importantly.
=> Upgrade game packages

osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
Will fix the missing PP sheets seen in:
https://github.com/ppy/osu/pull/28005#issuecomment-2079283702
https://github.com/ppy/osu/pull/27303#issuecomment-2072558859
=> Fix missing beatmap when running score PP processing via CLI

osu.Server.Queues.ScoreStatisticsProcessor/Helpers/UserTotalPerformanceAggregateHelper.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/ManiaKeyModeUserStatsProcessor.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/UserTotalPerformanceProcessor.cs
As seen at https://sentry.ppy.sh/organizations/ppy/issues/48654/?project=10. Clamping is the best solution.
=> Fix floating point inaccuracy triggering unexpected errors

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyImportedScoresCommand.cs
Closes https://github.com/ppy/osu-web/issues/11239.
=> Update verify-imported-scores command to never delete pinned scores

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Helpers/SlaveLatencyChecker.cs
For reuse in upcoming commands
=> Split latency checker out into a helper class

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/Scores/UpdateAllScoresCommand.cs
See individual commit messages
Already using the max PP paramteter on production run.
=> Add new process modes to score processing command

osu.Server.Queues.ScoreStatisticsProcessor/Commands/Performance/PerformanceCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/ManiaKeyModeUserStatsProcessor.cs
Opening this for self testing / review
- Closes #295
=> Fix multiple issues related to mania key count stats population

osu.Server.Queues.ScoreStatisticsProcessor.Tests/osu.Server.Queues.ScoreStatisticsProcessor.Tests.csproj, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyScoreRanksCommand.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/MaintenanceCommands.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScore.cs, osu.Server.Queues.ScoreStatisticsProcessor/osu.Server.Queues.ScoreStatisticsProcessor.csproj
=> Add command to reprocess score ranks

osu.Server.Queues.ScoreStatisticsProcessor.Tests/DailySproutTest.cs, osu.Server.Queues.ScoreStatisticsProcessor/Helpers/MedalHelpers.cs
Probably not a good idea to be opening this today given the magnitude of the original blunder but I will not be able to sleep tonight if I don't at least attempt to fix this. Please give this a lot of scrutiny.
=> Fix flagrantly incorrect query

osu.Server.Queues.ScoreStatisticsProcessor.Tests/MedalProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/MedalAwarders/PackMedalAwarder.cs
See https://osu.ppy.sh/community/forums/topics/2024188?n=2 for rationale.
=> Enable pack medal awarder for legacy scores

osu.Server.Queues.ScoreStatisticsProcessor/Processors/ScorePerformanceProcessor.cs
For consistency's sake, we most definitely want this to be the case.
=> Ensure pp is saved back to model when calculated

osu.Server.Queues.ScoreStatisticsProcessor.Tests/ManiaKeyModeUserStatsProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/Maintenance/VerifyUserRankedScore.cs, osu.Server.Queues.ScoreStatisticsProcessor/Commands/MaintenanceCommands.cs, osu.Server.Queues.ScoreStatisticsProcessor/Models/UserStatsManiaKeyCount.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/ManiaKeyModeUserStatsProcessor.cs
Requested by web team for https://github.com/ppy/osu-web/pull/12012.
Have tested to the best I can on production (verify command at least). Will run post-deploy so we don't have any non-tracked period.
=> Add support for mania variant ranked score bookkeeping and verification

osu.Server.Queues.ScoreStatisticsProcessor.Tests/ManiaKeyModeUserStatsProcessorTests.cs, osu.Server.Queues.ScoreStatisticsProcessor/Processors/ManiaKeyModeUserStatsProcessor.cs
The TODO about key mods is one thing, the flagrantly idiotic reinterpretation of `diff_size` as key count always regardless of original beatmap ruleset is another.
This is not a complete solution because the "initial playcount estimation" is pretty much infeasible to include converts in, but it is at least supposed to stop the bleeding on some complete idiocy.
And yeah this will likely also mean recomputation of these stats game wide. Probably.
I would ask who bungled the previous implementation *that* badly, but I know I would need to look in the mirror to answer that question.
---
The alternative solution here would be to delete converts from consideration via another guard, probably like so:
```diff
diff --git a/osu.Server.Queues.ScoreStatisticsProcessor/Processors/ManiaKeyModeUserStats …
```
=> Fix mania keymode user stats processor completely bungling convert treatment

osu.Server.Queues.ScoreStatisticsProcessor/Processors/HighBeatmapLeaderboardRankEventEmitter.cs
- Part of https://github.com/ppy/osu-infrastructure/issues/27
Compare [web-10 logic](https://github.com/peppy/osu-web-10/blob/c909557094210053f169c6d5dacef97d92e82864/www/web/osu-submit-20190809.php#L1214-L1215).
=> Emit first place lost events and update beatmap leaders
